# Nixpacks Configuration
# https://nixpacks.com/docs/configuration/file

[phases.setup]
nixPkgs = ["jdk21", "gradle"]

[phases.build]
cmds = [
  "chmod +x gradlew",
  "./gradlew clean build -x check -x test"
]

[start]
cmd = "java -jar build/libs/users-0.0.1-SNAPSHOT.jar"
